import type { DemoCaseFull } from "@/lib/demo-source";

/**
 * Предзаписанные демо-кейсы. Поля и структура соответствуют выходу пайплайна
 * (типы invoice/factInvoice/UPD/TTN/CMR/AKT). Превью отрисовывается как
 * «бумага» из previewLines — реальные PNG-сканы можно подставить позже,
 * не меняя UI (см. StaticDemoSource).
 */
export const demoCases: DemoCaseFull[] = [
  {
    id: "invoice",
    label: "Счёт на оплату",
    docTypeSlug: "invoice",
    category: "accounting",
    icon: "ReceiptText",
    previewTitle: "СЧЁТ НА ОПЛАТУ № СЧ-1042",
    previewSubtitle: "от 19 мая 2026 г.",
    previewLines: [
      "Поставщик: ООО «Негабарит», ИНН 7802338201, КПП 780201001",
      "Покупатель: ООО «Антарес», ИНН 7706094528",
      "",
      "1. Перевозка негабаритного груза СПб–Москва  ... 405 000,00",
      "2. Услуги сопровождения  .......................  81 000,00",
      "",
      "Итого: 486 000,00    В т.ч. НДС 20%: 81 000,00",
      "Всего к оплате: четыреста восемьдесят шесть тысяч руб.",
    ],
    result: {
      type: "invoice",
      confidence: 0.97,
      ocrEngine: "pdf-text",
      timings: [
        { stage: "ocr", ms: 180 },
        { stage: "classify", ms: 240 },
        { stage: "extract", ms: 610 },
        { stage: "validate", ms: 120 },
      ],
      fields: [
        { label: "Номер", value: "СЧ-1042" },
        { label: "Дата", value: "2026-05-19" },
        { label: "Поставщик", value: "ООО «Негабарит»" },
        { label: "ИНН поставщика", value: "7802338201" },
        { label: "Покупатель", value: "ООО «Антарес»" },
        { label: "Итого", value: "486 000,00 ₽" },
        { label: "НДС 20%", value: "81 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "КПП", ok: true },
        { label: "НДС консистентен", ok: true },
        { label: "Сумма позиций = итог", ok: true },
      ],
      json: {
        type: "invoice",
        confidence: 0.97,
        number: "СЧ-1042",
        date: "2026-05-19",
        seller: { name: "ООО «Негабарит»", inn: "7802338201", kpp: "780201001" },
        buyer: { name: "ООО «Антарес»", inn: "7706094528" },
        positions: [
          { name: "Перевозка негабаритного груза СПб–Москва", total: 405000.0 },
          { name: "Услуги сопровождения", total: 81000.0 },
        ],
        total: 486000.0,
        vat: 81000.0,
        validation: { inn: "ok", kpp: "ok", vat: "ok", totals: "ok" },
      },
    },
  },
  {
    id: "factInvoice",
    label: "Счёт-фактура",
    docTypeSlug: "factInvoice",
    category: "accounting",
    icon: "FileSpreadsheet",
    previewTitle: "СЧЁТ-ФАКТУРА № 114",
    previewSubtitle: "от 19 мая 2026 г.",
    previewLines: [
      "Продавец: ООО «Негабарит», ИНН/КПП 7802338201 / 780201001",
      "Покупатель: ООО «Антарес», ИНН/КПП 7706094528 / 770601001",
      "",
      "Товары (работы, услуги) ... Стоимость без налога: 405 000,00",
      "Налоговая ставка: 20%   Сумма налога: 79 800,00",
      "Стоимость с налогом: 486 000,00",
      "",
      "(скан, подпись и печать)",
    ],
    result: {
      type: "factInvoice",
      confidence: 0.93,
      ocrEngine: "vision-llm",
      timings: [
        { stage: "ocr", ms: 1840 },
        { stage: "classify", ms: 260 },
        { stage: "extract", ms: 720 },
        { stage: "validate", ms: 140 },
      ],
      fields: [
        { label: "Номер", value: "114" },
        { label: "Дата", value: "2026-05-19" },
        { label: "Продавец", value: "ООО «Негабарит»" },
        { label: "Покупатель", value: "ООО «Антарес»" },
        { label: "Без налога", value: "405 000,00 ₽" },
        { label: "НДС 20%", value: "79 800,00 ₽" },
        { label: "С налогом", value: "486 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "КПП", ok: true },
        {
          label: "НДС консистентен",
          ok: false,
          detail: "405 000 × 20% = 81 000, в документе 79 800",
        },
      ],
      json: {
        type: "factInvoice",
        confidence: 0.93,
        status: "needs_review",
        number: "114",
        date: "2026-05-19",
        seller: { name: "ООО «Негабарит»", inn: "7802338201", kpp: "780201001" },
        buyer: { name: "ООО «Антарес»", inn: "7706094528", kpp: "770601001" },
        amount_no_vat: 405000.0,
        vat_rate: 20,
        vat: 79800.0,
        amount_with_vat: 486000.0,
        validation: { inn: "ok", kpp: "ok", vat: "mismatch" },
      },
    },
  },
  {
    id: "upd",
    label: "УПД",
    docTypeSlug: "UPD",
    category: "accounting",
    icon: "FileCheck2",
    previewTitle: "УНИВЕРСАЛЬНЫЙ ПЕРЕДАТОЧНЫЙ ДОКУМЕНТ",
    previewSubtitle: "Статус: 1   № УПД-114 от 19.05.2026",
    previewLines: [
      "Продавец: ООО «Негабарит», ИНН 7802338201",
      "Покупатель: ООО «Антарес», ИНН 7706094528",
      "",
      "Наименование ... Кол-во ... Цена ... Стоимость с НДС",
      "Транспортные услуги ... 1 ... 486 000 ... 486 000,00",
      "",
      "Всего к оплате: 486 000,00   В т.ч. НДС: 81 000,00",
    ],
    result: {
      type: "UPD",
      confidence: 0.98,
      ocrEngine: "pdf-text",
      timings: [
        { stage: "ocr", ms: 160 },
        { stage: "classify", ms: 210 },
        { stage: "extract", ms: 560 },
        { stage: "validate", ms: 110 },
      ],
      fields: [
        { label: "Статус", value: "1 (счёт-фактура + накладная)" },
        { label: "Номер", value: "УПД-114" },
        { label: "Дата", value: "2026-05-19" },
        { label: "Продавец", value: "ООО «Негабарит»" },
        { label: "Покупатель", value: "ООО «Антарес»" },
        { label: "Всего к оплате", value: "486 000,00 ₽" },
        { label: "НДС", value: "81 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "НДС консистентен", ok: true },
        { label: "Сумма позиций = итог", ok: true },
      ],
      json: {
        type: "UPD",
        confidence: 0.98,
        status_code: 1,
        number: "УПД-114",
        date: "2026-05-19",
        seller: { name: "ООО «Негабарит»", inn: "7802338201" },
        buyer: { name: "ООО «Антарес»", inn: "7706094528" },
        total: 486000.0,
        vat: 81000.0,
        validation: { inn: "ok", vat: "ok", totals: "ok" },
      },
    },
  },
  {
    id: "ttn",
    label: "ТТН",
    docTypeSlug: "TTN",
    category: "transport",
    icon: "Truck",
    previewTitle: "ТРАНСПОРТНАЯ НАКЛАДНАЯ № 884",
    previewSubtitle: "от 18 мая 2026 г.",
    previewLines: [
      "Грузоотправитель: ООО «Негабарит»",
      "Грузополучатель: ООО «Антарес»",
      "Перевозчик: ИП Сидоров А. В.",
      "",
      "ТС: МАЗ 6430, госномер Е 432 КХ 178",
      "Прицеп: АМ 1789 78",
      "Груз: оборудование, 12 мест, 18 600 кг",
      "Маршрут: Санкт-Петербург → Москва",
    ],
    result: {
      type: "TTN",
      confidence: 0.95,
      ocrEngine: "tesseract",
      timings: [
        { stage: "ocr", ms: 920 },
        { stage: "classify", ms: 230 },
        { stage: "extract", ms: 640 },
        { stage: "validate", ms: 130 },
      ],
      fields: [
        { label: "Номер", value: "884" },
        { label: "Дата", value: "2026-05-18" },
        { label: "Грузоотправитель", value: "ООО «Негабарит»" },
        { label: "Грузополучатель", value: "ООО «Антарес»" },
        { label: "Перевозчик", value: "ИП Сидоров А. В." },
        { label: "ТС", value: "МАЗ 6430, Е432КХ178" },
        { label: "Масса груза", value: "18 600 кг" },
      ],
      validation: [
        { label: "Госномер ТС", ok: true },
        { label: "Госномер прицепа", ok: true },
        { label: "Маршрут распознан", ok: true },
      ],
      json: {
        type: "TTN",
        confidence: 0.95,
        number: "884",
        date: "2026-05-18",
        shipper: { name: "ООО «Негабарит»" },
        consignee: { name: "ООО «Антарес»" },
        carrier: { name: "ИП Сидоров А. В." },
        vehicle: { model: "МАЗ 6430", plate: "Е432КХ178", trailer: "АМ178978" },
        cargo: { places: 12, weight_kg: 18600 },
        route: { from: "Санкт-Петербург", to: "Москва" },
        validation: { plate: "ok", trailer_plate: "ok" },
      },
    },
  },
  {
    id: "cmr",
    label: "CMR",
    docTypeSlug: "CMR",
    category: "transport",
    icon: "Globe",
    previewTitle: "CMR — INTERNATIONAL CONSIGNMENT NOTE",
    previewSubtitle: "№ 0042189",
    previewLines: [
      "1 Sender: OOO Negabarit, St. Petersburg, RU",
      "2 Consignee: Antares GmbH, Berlin, DE",
      "4 Place of loading: Saint-Petersburg (RU)",
      "5 Place of delivery: Berlin (DE)",
      "16 Carrier: TransEU sp. z o.o.",
      "Goods: machinery, 12 pkg, 18 600 kg",
    ],
    result: {
      type: "CMR",
      confidence: 0.9,
      ocrEngine: "vision-llm",
      timings: [
        { stage: "ocr", ms: 2010 },
        { stage: "classify", ms: 280 },
        { stage: "extract", ms: 760 },
        { stage: "validate", ms: 120 },
      ],
      fields: [
        { label: "Номер", value: "0042189" },
        { label: "Отправитель", value: "OOO Negabarit (RU)" },
        { label: "Получатель", value: "Antares GmbH (DE)" },
        { label: "Погрузка", value: "Санкт-Петербург" },
        { label: "Доставка", value: "Берлин" },
        { label: "Перевозчик", value: "TransEU sp. z o.o." },
        { label: "Груз", value: "12 мест, 18 600 кг" },
      ],
      validation: [
        { label: "Страны маршрута", ok: true },
        { label: "Места/вес распознаны", ok: true },
      ],
      json: {
        type: "CMR",
        confidence: 0.9,
        number: "0042189",
        sender: { name: "OOO Negabarit", country: "RU" },
        consignee: { name: "Antares GmbH", country: "DE" },
        loading: { place: "Saint-Petersburg", country: "RU" },
        delivery: { place: "Berlin", country: "DE" },
        carrier: { name: "TransEU sp. z o.o." },
        cargo: { packages: 12, weight_kg: 18600 },
        validation: { route_countries: "ok" },
      },
    },
  },
  {
    id: "akt",
    label: "Акт услуг",
    docTypeSlug: "AKT",
    category: "accounting",
    icon: "FileSignature",
    previewTitle: "АКТ № 207 оказанных услуг",
    previewSubtitle: "от 20 мая 2026 г.",
    previewLines: [
      "Исполнитель: ООО «Негабарит», ИНН 7802338201",
      "Заказчик: ООО «Антарес», ИНН 7706094528",
      "",
      "Услуга: перевозка негабаритного груза по маршруту СПб–Москва",
      "Стоимость: 486 000,00, в т.ч. НДС 20% — 81 000,00",
      "",
      "Услуги оказаны полностью, претензий нет.",
    ],
    result: {
      type: "AKT",
      confidence: 0.96,
      ocrEngine: "pdf-text",
      timings: [
        { stage: "ocr", ms: 170 },
        { stage: "classify", ms: 200 },
        { stage: "extract", ms: 520 },
        { stage: "validate", ms: 100 },
      ],
      fields: [
        { label: "Номер", value: "207" },
        { label: "Дата", value: "2026-05-20" },
        { label: "Исполнитель", value: "ООО «Негабарит»" },
        { label: "Заказчик", value: "ООО «Антарес»" },
        { label: "Сумма", value: "486 000,00 ₽" },
        { label: "НДС 20%", value: "81 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "НДС консистентен", ok: true },
      ],
      json: {
        type: "AKT",
        confidence: 0.96,
        number: "207",
        date: "2026-05-20",
        contractor: { name: "ООО «Негабарит»", inn: "7802338201" },
        customer: { name: "ООО «Антарес»", inn: "7706094528" },
        service: "Перевозка негабаритного груза СПб–Москва",
        total: 486000.0,
        vat: 81000.0,
        validation: { inn: "ok", vat: "ok" },
      },
    },
  },
];
