import type { DemoCaseFull } from "@/lib/demo-source";

/**
 * Предзаписанные демо-кейсы. `doc` — данные для отрисовки реалистичного
 * превью документа (шапка, реквизиты, таблица, итоги, печать/подпись).
 * `result` — предзаписанный выход пайплайна (тип/поля/валидация/тайминги).
 * Данные синтетические, но в формате реальных российских документов.
 */
export const demoCases: DemoCaseFull[] = [
  {
    id: "invoice",
    label: "Счёт на оплату",
    docTypeSlug: "invoice",
    category: "accounting",
    icon: "ReceiptText",
    doc: {
      kind: "accounting",
      org: "ООО «Негабарит»",
      title: "Счёт на оплату № СЧ-1042",
      number: "СЧ-1042",
      date: "19 мая 2026 г.",
      parties: [
        {
          role: "Поставщик",
          name: "ООО «Негабарит»",
          inn: "7802338201",
          kpp: "780201001",
          address: "194354, Санкт-Петербург, ул. Сикейроса, д. 6",
        },
        { role: "Покупатель", name: "ООО «Антарес»", inn: "7706094528" },
      ],
      items: [
        {
          name: "Перевозка негабаритного груза СПб — Москва",
          qty: "1",
          price: "405 000,00",
          sum: "405 000,00",
        },
        {
          name: "Услуги сопровождения (2 ед.)",
          qty: "2",
          price: "40 500,00",
          sum: "81 000,00",
        },
      ],
      total: "486 000,00",
      vat: "81 000,00",
      signer: "Ляпустин А. Ю.",
    },
    result: {
      type: "invoice",
      confidence: 0.97,
      ocrEngine: "pdf-text",
      timings: [
        { stage: "ocr", ms: 180 },
        { stage: "classify", ms: 240 },
        { stage: "extract", ms: 610 },
        { stage: "validate", ms: 120 },
      ],
      fields: [
        { label: "Номер", value: "СЧ-1042" },
        { label: "Дата", value: "2026-05-19" },
        { label: "Поставщик", value: "ООО «Негабарит»" },
        { label: "ИНН поставщика", value: "7802338201" },
        { label: "Покупатель", value: "ООО «Антарес»" },
        { label: "Итого", value: "486 000,00 ₽" },
        { label: "НДС 20%", value: "81 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "КПП", ok: true },
        { label: "НДС консистентен", ok: true },
        { label: "Сумма позиций = итог", ok: true },
      ],
      json: {
        type: "invoice",
        confidence: 0.97,
        number: "СЧ-1042",
        date: "2026-05-19",
        seller: { name: "ООО «Негабарит»", inn: "7802338201", kpp: "780201001" },
        buyer: { name: "ООО «Антарес»", inn: "7706094528" },
        positions: [
          { name: "Перевозка негабаритного груза СПб–Москва", total: 405000.0 },
          { name: "Услуги сопровождения", total: 81000.0 },
        ],
        total: 486000.0,
        vat: 81000.0,
        validation: { inn: "ok", kpp: "ok", vat: "ok", totals: "ok" },
      },
    },
  },
  {
    id: "factInvoice",
    label: "Счёт-фактура",
    docTypeSlug: "factInvoice",
    category: "accounting",
    icon: "FileSpreadsheet",
    doc: {
      kind: "accounting",
      org: "ООО «Негабарит»",
      title: "Счёт-фактура № 114",
      number: "114",
      date: "19 мая 2026 г.",
      parties: [
        {
          role: "Продавец",
          name: "ООО «Негабарит»",
          inn: "7802338201",
          kpp: "780201001",
        },
        {
          role: "Покупатель",
          name: "ООО «Антарес»",
          inn: "7706094528",
          kpp: "770601001",
        },
      ],
      items: [
        {
          name: "Транспортно-экспедиционные услуги",
          qty: "1",
          price: "405 000,00",
          sum: "405 000,00",
        },
      ],
      total: "486 000,00",
      vat: "79 800,00",
      signer: "Ляпустин А. Ю.",
    },
    result: {
      type: "factInvoice",
      confidence: 0.93,
      ocrEngine: "vision-llm",
      timings: [
        { stage: "ocr", ms: 1840 },
        { stage: "classify", ms: 260 },
        { stage: "extract", ms: 720 },
        { stage: "validate", ms: 140 },
      ],
      fields: [
        { label: "Номер", value: "114" },
        { label: "Дата", value: "2026-05-19" },
        { label: "Продавец", value: "ООО «Негабарит»" },
        { label: "Покупатель", value: "ООО «Антарес»" },
        { label: "Без налога", value: "405 000,00 ₽" },
        { label: "НДС 20%", value: "79 800,00 ₽" },
        { label: "С налогом", value: "486 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "КПП", ok: true },
        {
          label: "НДС консистентен",
          ok: false,
          detail: "405 000 × 20% = 81 000, в документе 79 800",
        },
      ],
      json: {
        type: "factInvoice",
        confidence: 0.93,
        status: "needs_review",
        number: "114",
        date: "2026-05-19",
        seller: { name: "ООО «Негабарит»", inn: "7802338201", kpp: "780201001" },
        buyer: { name: "ООО «Антарес»", inn: "7706094528", kpp: "770601001" },
        amount_no_vat: 405000.0,
        vat_rate: 20,
        vat: 79800.0,
        amount_with_vat: 486000.0,
        validation: { inn: "ok", kpp: "ok", vat: "mismatch" },
      },
    },
  },
  {
    id: "upd",
    label: "УПД",
    docTypeSlug: "UPD",
    category: "accounting",
    icon: "FileCheck2",
    doc: {
      kind: "accounting",
      org: "ООО «Негабарит»",
      title: "Универсальный передаточный документ",
      number: "УПД-114",
      date: "19 мая 2026 г.",
      parties: [
        { role: "Продавец", name: "ООО «Негабарит»", inn: "7802338201" },
        { role: "Покупатель", name: "ООО «Антарес»", inn: "7706094528" },
      ],
      items: [
        {
          name: "Транспортные услуги по договору № 7",
          qty: "1",
          price: "405 000,00",
          sum: "486 000,00",
        },
      ],
      total: "486 000,00",
      vat: "81 000,00",
      signer: "Ляпустин А. Ю.",
    },
    result: {
      type: "UPD",
      confidence: 0.98,
      ocrEngine: "pdf-text",
      timings: [
        { stage: "ocr", ms: 160 },
        { stage: "classify", ms: 210 },
        { stage: "extract", ms: 560 },
        { stage: "validate", ms: 110 },
      ],
      fields: [
        { label: "Статус", value: "1 (счёт-фактура + накладная)" },
        { label: "Номер", value: "УПД-114" },
        { label: "Дата", value: "2026-05-19" },
        { label: "Продавец", value: "ООО «Негабарит»" },
        { label: "Покупатель", value: "ООО «Антарес»" },
        { label: "Всего к оплате", value: "486 000,00 ₽" },
        { label: "НДС", value: "81 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "НДС консистентен", ok: true },
        { label: "Сумма позиций = итог", ok: true },
      ],
      json: {
        type: "UPD",
        confidence: 0.98,
        status_code: 1,
        number: "УПД-114",
        date: "2026-05-19",
        seller: { name: "ООО «Негабарит»", inn: "7802338201" },
        buyer: { name: "ООО «Антарес»", inn: "7706094528" },
        total: 486000.0,
        vat: 81000.0,
        validation: { inn: "ok", vat: "ok", totals: "ok" },
      },
    },
  },
  {
    id: "ttn",
    label: "ТТН",
    docTypeSlug: "TTN",
    category: "transport",
    icon: "Truck",
    doc: {
      kind: "transport",
      org: "ООО «Негабарит»",
      title: "Транспортная накладная № 884",
      number: "884",
      date: "18 мая 2026 г.",
      parties: [
        { role: "Грузоотправитель", name: "ООО «Негабарит»", inn: "7802338201" },
        { role: "Грузополучатель", name: "ООО «Антарес»", inn: "7706094528" },
        { role: "Перевозчик", name: "ИП Сидоров А. В.", inn: "781305229100" },
      ],
      rows: [
        { k: "Транспортное средство", v: "МАЗ 6430, Е 432 КХ 178" },
        { k: "Прицеп", v: "АМ 1789 78" },
        { k: "Груз", v: "Оборудование, 12 мест" },
        { k: "Масса брутто", v: "18 600 кг" },
        { k: "Маршрут", v: "Санкт-Петербург → Москва" },
      ],
      signer: "Сидоров А. В.",
    },
    result: {
      type: "TTN",
      confidence: 0.95,
      ocrEngine: "tesseract",
      timings: [
        { stage: "ocr", ms: 920 },
        { stage: "classify", ms: 230 },
        { stage: "extract", ms: 640 },
        { stage: "validate", ms: 130 },
      ],
      fields: [
        { label: "Номер", value: "884" },
        { label: "Дата", value: "2026-05-18" },
        { label: "Грузоотправитель", value: "ООО «Негабарит»" },
        { label: "Грузополучатель", value: "ООО «Антарес»" },
        { label: "Перевозчик", value: "ИП Сидоров А. В." },
        { label: "ТС", value: "МАЗ 6430, Е432КХ178" },
        { label: "Масса груза", value: "18 600 кг" },
      ],
      validation: [
        { label: "Госномер ТС", ok: true },
        { label: "Госномер прицепа", ok: true },
        { label: "Маршрут распознан", ok: true },
      ],
      json: {
        type: "TTN",
        confidence: 0.95,
        number: "884",
        date: "2026-05-18",
        shipper: { name: "ООО «Негабарит»" },
        consignee: { name: "ООО «Антарес»" },
        carrier: { name: "ИП Сидоров А. В." },
        vehicle: { model: "МАЗ 6430", plate: "Е432КХ178", trailer: "АМ178978" },
        cargo: { places: 12, weight_kg: 18600 },
        route: { from: "Санкт-Петербург", to: "Москва" },
        validation: { plate: "ok", trailer_plate: "ok" },
      },
    },
  },
  {
    id: "cmr",
    label: "CMR",
    docTypeSlug: "CMR",
    category: "transport",
    icon: "Globe",
    doc: {
      kind: "transport",
      org: "OOO Negabarit",
      title: "CMR — International Consignment Note № 0042189",
      number: "0042189",
      date: "17 мая 2026 г.",
      parties: [
        { role: "Sender (1)", name: "OOO Negabarit", address: "St. Petersburg, RU" },
        { role: "Consignee (2)", name: "Antares GmbH", address: "Berlin, DE" },
        { role: "Carrier (16)", name: "TransEU sp. z o.o.", address: "Warszawa, PL" },
      ],
      rows: [
        { k: "Place of loading (4)", v: "Saint-Petersburg (RU)" },
        { k: "Place of delivery (5)", v: "Berlin (DE)" },
        { k: "Goods (6–9)", v: "Machinery, 12 packages" },
        { k: "Gross weight (11)", v: "18 600 kg" },
      ],
      signer: "TransEU sp. z o.o.",
    },
    result: {
      type: "CMR",
      confidence: 0.9,
      ocrEngine: "vision-llm",
      timings: [
        { stage: "ocr", ms: 2010 },
        { stage: "classify", ms: 280 },
        { stage: "extract", ms: 760 },
        { stage: "validate", ms: 120 },
      ],
      fields: [
        { label: "Номер", value: "0042189" },
        { label: "Отправитель", value: "OOO Negabarit (RU)" },
        { label: "Получатель", value: "Antares GmbH (DE)" },
        { label: "Погрузка", value: "Санкт-Петербург" },
        { label: "Доставка", value: "Берлин" },
        { label: "Перевозчик", value: "TransEU sp. z o.o." },
        { label: "Груз", value: "12 мест, 18 600 кг" },
      ],
      validation: [
        { label: "Страны маршрута", ok: true },
        { label: "Места/вес распознаны", ok: true },
      ],
      json: {
        type: "CMR",
        confidence: 0.9,
        number: "0042189",
        sender: { name: "OOO Negabarit", country: "RU" },
        consignee: { name: "Antares GmbH", country: "DE" },
        loading: { place: "Saint-Petersburg", country: "RU" },
        delivery: { place: "Berlin", country: "DE" },
        carrier: { name: "TransEU sp. z o.o." },
        cargo: { packages: 12, weight_kg: 18600 },
        validation: { route_countries: "ok" },
      },
    },
  },
  {
    id: "akt",
    label: "Акт услуг",
    docTypeSlug: "AKT",
    category: "accounting",
    icon: "FileSignature",
    doc: {
      kind: "accounting",
      org: "ООО «Негабарит»",
      title: "Акт № 207 оказанных услуг",
      number: "207",
      date: "20 мая 2026 г.",
      parties: [
        { role: "Исполнитель", name: "ООО «Негабарит»", inn: "7802338201" },
        { role: "Заказчик", name: "ООО «Антарес»", inn: "7706094528" },
      ],
      items: [
        {
          name: "Перевозка негабаритного груза СПб — Москва",
          qty: "1",
          price: "405 000,00",
          sum: "486 000,00",
        },
      ],
      total: "486 000,00",
      vat: "81 000,00",
      signer: "Ляпустин А. Ю.",
    },
    result: {
      type: "AKT",
      confidence: 0.96,
      ocrEngine: "pdf-text",
      timings: [
        { stage: "ocr", ms: 170 },
        { stage: "classify", ms: 200 },
        { stage: "extract", ms: 520 },
        { stage: "validate", ms: 100 },
      ],
      fields: [
        { label: "Номер", value: "207" },
        { label: "Дата", value: "2026-05-20" },
        { label: "Исполнитель", value: "ООО «Негабарит»" },
        { label: "Заказчик", value: "ООО «Антарес»" },
        { label: "Сумма", value: "486 000,00 ₽" },
        { label: "НДС 20%", value: "81 000,00 ₽" },
      ],
      validation: [
        { label: "ИНН", ok: true },
        { label: "НДС консистентен", ok: true },
      ],
      json: {
        type: "AKT",
        confidence: 0.96,
        number: "207",
        date: "2026-05-20",
        contractor: { name: "ООО «Негабарит»", inn: "7802338201" },
        customer: { name: "ООО «Антарес»", inn: "7706094528" },
        service: "Перевозка негабаритного груза СПб–Москва",
        total: 486000.0,
        vat: 81000.0,
        validation: { inn: "ok", vat: "ok" },
      },
    },
  },
];
